#!/bin/bash

set -e -o pipefail

SCRIPT_NAME='genisys-upsert-monitor-device'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == "$DEBUG" ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_device_type() {
  local meshblu_json_path device device_type required_device_type
  meshblu_json_path="$1"
  required_device_type="$2"

  device="$(meshblu-util get "$meshblu_json_path")" || fatal "Could not retrieve device described at </path/to/customer/meshblu.json>"
  device_type="$(echo "$device" | jq --raw-output '.type')" || fatal "Could not parse device JSON returned from meshblu"

  if [ "$device_type" != "$required_device_type" ]; then
    err_echo "Device described at '$meshblu_json_path' must be '$required_device_type', received: '$device_type'"
    exit 1
  fi
}

assert_required_params() {
  local meshblu_json_path="$1"

  if [ -n "$meshblu_json_path" ] && [ -f "$meshblu_json_path" ]; then
    return 0
  fi

  usage

  if [ -z "$meshblu_json_path" ]; then
    echo "Missing </path/to/customer/meshblu.json> argument"
  elif [ ! -f "$meshblu_json_path" ]; then
    echo "Could not find a file at '$meshblu_json_path'"
  fi

  exit 1
}

usage(){
  echo "USAGE: ${SCRIPT_NAME} </path/to/customer/meshblu.json>"
  echo ''
  echo 'Description: Create a new device for use with the interaction monitor.'
  echo '             It will be setup with subscriptions to the customer'
  echo '             devices, which will also get you the room/user messages (I think)'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help       print this help text'
  echo '  -v, --version    print the version'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory
  directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

create_monitor() {
  set -e -o pipefail # early return if anything returns a non 0
  local customer_meshblu_json_path customer_uuid monitor_uuid
  customer_meshblu_json_path="$1"

  customer_uuid="$(jq --raw-output '.uuid' "$customer_meshblu_json_path")"

  monitor_meshblu_json_path="$(dirname "$customer_meshblu_json_path")/../interaction-monitor/meshblu.json"

  mkdir -p "$(dirname "$monitor_meshblu_json_path")"

  # Register new device
  meshblu-util register \
    "$customer_meshblu_json_path" \
  > "$monitor_meshblu_json_path"

  # Update with customer in configure.update whitelist
  meshblu-util update \
    --data "{\"meshblu.whitelists.configure.update\":[{\"uuid\":\"$customer_uuid\"}]}" \
    "$monitor_meshblu_json_path"

  # Update with customer in discover.view whitelist
  meshblu-util update \
    --data "{\"meshblu.whitelists.discover.view\":[{\"uuid\":\"$customer_uuid\"}]}" \
    "$monitor_meshblu_json_path"

  monitor_uuid="$(jq --join-output '.uuid' "$monitor_meshblu_json_path")"

  # Update customer with interactionMonitor
  meshblu-util update \
    --data "{\"genisys.devices.interactionMonitor.uuid\":\"$monitor_uuid\"}" \
    "$customer_meshblu_json_path"

  echo -n "$monitor_uuid"
}

find_or_create_monitor(){
  set -e -o pipefail # early return if anything returns a non 0
  local meshblu_json_path monitor_uuid
  meshblu_json_path="$1"

  monitor_uuid="$(meshblu-util get "$meshblu_json_path" | jq --raw-output '.genisys.devices.interactionMonitor.uuid')"

  if [ "$monitor_uuid" != "null" ]; then
    echo -n "$monitor_uuid"
    return 0
  fi

  create_monitor "$meshblu_json_path"
}

get_customer_devices(){
  set -e -o pipefail # early return if anything returns a non 0
  local meshblu_json_path
  meshblu_json_path="$1"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices | to_entries[].value.uuid'
}

create_subscription(){
  set -e -o pipefail # early return if anything returns a non 0
  local meshblu_json_path monitor_uuid device_uuid subscription_type
  meshblu_json_path="$1"
  monitor_uuid="$2"
  device_uuid="$3"
  subscription_type="$4"

  meshblu-util update \
    --uuid "$device_uuid" \
    --put \
    --data "{\"\$addToSet\": {\"meshblu.whitelists.$subscription_type\": {\"uuid\":\"$monitor_uuid\"}, \"meshblu.whitelists.discover.view\": {\"uuid\":\"$monitor_uuid\"}}}" \
    "$meshblu_json_path"

  meshblu-util subscription-create \
    --subscriber "$monitor_uuid" \
    --emitter "$device_uuid" \
    --type "$subscription_type" \
    "$meshblu_json_path"
}

create_subscriptions(){
  set -e -o pipefail # early return if anything returns a non 0
  local meshblu_json_path monitor_uuid device_uuid
  meshblu_json_path="$1"
  monitor_uuid="$2"
  device_uuid="$3"

  create_subscription "$meshblu_json_path" "$monitor_uuid" "$device_uuid" "broadcast.received"
  create_subscription "$meshblu_json_path" "$monitor_uuid" "$device_uuid" "configure.received"
  create_subscription "$meshblu_json_path" "$monitor_uuid" "$device_uuid" "message.received"
  create_subscription "$meshblu_json_path" "$monitor_uuid" "$device_uuid" "broadcast.sent"
  create_subscription "$meshblu_json_path" "$monitor_uuid" "$device_uuid" "configure.sent"
  create_subscription "$meshblu_json_path" "$monitor_uuid" "$device_uuid" "message.sent"
}

update_monitor(){
  set -e -o pipefail # early return if anything returns a non 0
  local customer_meshblu_json_path customer_uuid monitor_uuid
  customer_meshblu_json_path="$1"
  monitor_uuid="$2"

  customer_uuid="$(jq --join-output '.uuid' "$customer_meshblu_json_path")"

  meshblu-util update \
    --uuid "$monitor_uuid" \
    --put \
    --data "{\"\$addToSet\": {\"meshblu.whitelists.discover.view\": {\"uuid\": \"$customer_uuid\"}}}" \
    "$customer_meshblu_json_path"
}

upsert_monitor(){
  local meshblu_json_path monitor_uuid customer_devices customer_uuid
  meshblu_json_path="$1"

  monitor_uuid="$(find_or_create_monitor "$meshblu_json_path")"
  update_monitor "$meshblu_json_path" "$monitor_uuid"
  customer_devices=( $(get_customer_devices "$meshblu_json_path") )
  customer_uuid="$(jq --join-output '.uuid' "$meshblu_json_path")"

  create_subscriptions "$meshblu_json_path" "$monitor_uuid" "$customer_uuid"
  for customer_device in "${customer_devices[@]}"; do
    create_subscriptions "$meshblu_json_path" "$monitor_uuid" "$customer_device"
  done
}

main() {
  local meshblu_json_path

  # Define args up here
  while [ "$1" != "" ]; do
    local param="$1"
    # local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      # Arg with value
      # -x | --example)
      #   example="$value"
      #   shift
      #   ;;
      # Arg without value
      # -e | --example-flag)
      #   example_flag='true'
      #   ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$meshblu_json_path" ]; then
          meshblu_json_path="$param"
        # elif [ -z "$main_arg_2"]; then
        #   main_arg_2="$param"
        fi
        ;;
    esac
    shift
  done

  assert_required_params "$meshblu_json_path"
  assert_device_type "$meshblu_json_path" "octoblu:smartspaces:customer"

  upsert_monitor "$meshblu_json_path"
}

main "$@"
