#!/bin/bash

SCRIPT_NAME='genisys-restart-slurries'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == "$DEBUG" ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

err_echo() {
  local message="$1"
  echo "$message" 1>&2
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_required_params() {
  local path_to_rooms="$1"

  if [ -n "$path_to_rooms" ] && [ -d "$path_to_rooms" ]; then
    return 0
  fi

  usage

  if [ -z "$path_to_rooms" ]; then
    err_echo "Missing example_arg argument"
  elif [ ! -d "$path_to_rooms" ]; then
    err_echo "Could not find a directory at '$path_to_rooms'"
  fi

  exit 1
}

usage(){
  echo 'USAGE:'
  echo "  ${SCRIPT_NAME} [/path/to/rooms]"
  echo ''
  echo 'Description:'
  echo '  Iterates through all the rooms and does a meshblu update'
  echo '  to set the meshblu.updatedAt to the current time, triggering'
  echo '  a configure.sent message that restarts the slurry'
  echo '  [/path/to/rooms] defaults to .'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help       print this help text'
  echo '  -v, --version    print the version'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory
  directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

restart_slurries() {
  local path_to_rooms rooms
  path_to_rooms="$1"
  rooms=( $(find "$path_to_rooms" -type d -mindepth 1 -maxdepth 1) )

  for room in "${rooms[@]}"; do
    restart_slurry "$room/slurry-exchange/meshblu.json" || err_echo "error restarting '$room', moving on..."
  done
}

restart_slurry() {
  local current_time meshblu_json_path
  meshblu_json_path="$1"
  current_time="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

  echo "$meshblu_json_path"
  meshblu-util update -d "{\"meshblu.updatedAt\": \"$current_time\"}" "$meshblu_json_path"
}

main() {
  local path_to_rooms

  # Define args up here
  while [ "$1" != "" ]; do
    local param="$1"
    # local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      # Arg with value
      # -x | --example)
      #   example="$value"
      #   shift
      #   ;;
      # Arg without value
      # -e | --example-flag)
      #   example_flag='true'
      #   ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$path_to_rooms" ]; then
          path_to_rooms="$param"
        # elif [ -z "$main_arg_2"]; then
        #   main_arg_2="$param"
        fi
        ;;
    esac
    shift
  done

  path_to_rooms="${path_to_rooms:-.}"

  assert_required_params "$path_to_rooms"
  restart_slurries "$path_to_rooms"
}

main "$@"
