#!/bin/bash

set -o pipefail
SCRIPT_NAME='find-group-devices'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == $DEBUG ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_customer_json() {
  local meshblu_json_path="$1"
  local device_uuid
  device_uuid="$(jq --raw-output '.uuid' "$meshblu_json_path")"
  local exit_code=$?
  if [ "$exit_code" != "0" ]; then
    exit $exit_code
  fi

  local device_type="$(get_device_type "$meshblu_json_path" "$device_uuid")"

  if [ "$device_type" != "octoblu:smartspaces:customer" ]; then
    usage

    echo "meshblu.json must be a customer, however, I detected that it was a '$device_type'"
    exit 1
  fi
}

assert_required_params() {
  local meshblu_json_path="$1"

  if [ -n "$meshblu_json_path" ]; then
    return 0
  fi

  usage

  if [ -z "$meshblu_json_path" ]; then
    echo "Missing </path/to/customer/meshblu.json> argument"
  fi

  exit 1
}

get_device_type() {
  local meshblu_json_path="$1"
  local uuid="$2"
  local device

  device="$(meshblu-util get --uuid "$uuid" "$meshblu_json_path")"
  local exit_code=$?
  if [ "$exit_code" != "0" ]; then
    return $exit_code
  fi

  echo -n "$device" | jq --raw-output '.type'
}

usage(){
  echo "USAGE: ${SCRIPT_NAME} [/path/to/customer/meshblu.json]"
  echo ''
  echo 'Description: ...'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help       print this help text'
  echo '  -v, --version    print the version'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

find_hue_button_group() {
  local meshblu_json_path="$1"

  local hue_button_group_uuid="$(find_hue_button_group_uuid "$meshblu_json_path")"
  if [ -z "$hue_button_group_uuid" ]; then
    echo "Failed to resolve hue-button-group uuid"
    return 1
  fi

  mkdir -p hue-button-group \
  && meshblu-util generate-token --uuid "$hue_button_group_uuid" "$meshblu_json_path" > hue-button-group/meshblu.json
}

find_hue_button_group_uuid() {
  local meshblu_json_path="$1"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.hueButtonGroup.uuid'
}

find_user_group() {
  local meshblu_json_path="$1"

  local user_group_uuid="$(find_user_group_uuid "$meshblu_json_path")"
  if [ -z "$user_group_uuid" ]; then
    echo "Failed to resolve user-group uuid"
    return 1
  fi

  mkdir -p user-group \
  && meshblu-util generate-token --uuid "$user_group_uuid" "$meshblu_json_path" > user-group/meshblu.json
}

find_user_group_uuid() {
  local meshblu_json_path="$1"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.userGroup.uuid'
}

find_room_group() {
  local meshblu_json_path="$1"

  local room_group_uuid="$(find_room_group_uuid "$meshblu_json_path")"
  if [ -z "$room_group_uuid" ]; then
    echo "Failed to resolve room-group uuid"
    return 1
  fi

  mkdir -p room-group \
  && meshblu-util generate-token --uuid "$room_group_uuid" "$meshblu_json_path" > room-group/meshblu.json
}

find_room_group_uuid() {
  local meshblu_json_path="$1"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.roomGroup.uuid'
}

find_room_group_status() {
  local meshblu_json_path="$1"

  local room_group_status_uuid="$(find_room_group_status_uuid "$meshblu_json_path")"
  if [ -z "$room_group_status_uuid" ]; then
    echo "Failed to resolve room-group-status uuid"
    return 1
  fi

  mkdir -p room-group-status \
  && meshblu-util generate-token --uuid "$room_group_status_uuid" "$meshblu_json_path" > room-group-status/meshblu.json
}

find_room_group_status_uuid() {
  local meshblu_json_path="$1"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.roomGroupStatus.uuid'
}

find_skype_group() {
  local meshblu_json_path="$1"

  local skype_group_uuid="$(find_skype_group_uuid "$meshblu_json_path")"
  if [ -z "$skype_group_uuid" ]; then
    echo "Failed to resolve skype-group uuid"
    return 1
  fi

  mkdir -p skype-group \
  && meshblu-util generate-token --uuid "$skype_group_uuid" "$meshblu_json_path" > skype-group/meshblu.json
}

find_skype_group_uuid() {
  local meshblu_json_path="$1"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.skypeGroup.uuid'
}

find_meeting_group() {
  local meshblu_json_path="$1"

  local meeting_group_uuid="$(find_meeting_group_uuid "$meshblu_json_path")"
  if [ -z "$meeting_group_uuid" ]; then
    echo "Failed to resolve meeting-group uuid"
    return 1
  fi

  mkdir -p meeting-group \
  && meshblu-util generate-token --uuid "$meeting_group_uuid" "$meshblu_json_path" > meeting-group/meshblu.json
}

find_meeting_group_uuid() {
  local meshblu_json_path="$1"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.meetingGroup.uuid'
}

find_endo_genisys_meetings() {
  local meshblu_json_path="$1"

  local endo_genisys_meetings_uuid="$(find_endo_genisys_meetings_uuid "$meshblu_json_path")"
  if [ -z "$endo_genisys_meetings_uuid" ]; then
    echo "Failed to resolve endo genisys meeting uuid"
    return 1
  fi

  mkdir -p endo-genisys-meetings \
  && meshblu-util generate-token --uuid "$endo_genisys_meetings_uuid" "$meshblu_json_path" > endo-genisys-meetings/meshblu.json
}

find_endo_genisys_meetings_uuid() {
  local meshblu_json_path="$1"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.meetingGroupEndoMeeting.uuid'
}

find_device() {
  local name="$1"
  local genisys_device_name="$2"
  local meshblu_json_path="$3"

  local device_uuid="$(find_device_uuid "$genisys_device_name" "$meshblu_json_path")"
  if [ -z "$device_uuid" ]; then
    echo "Failed to resolve $name"
    return 1
  fi

  mkdir -p "$name" \
  && meshblu-util generate-token --uuid "$device_uuid" "$meshblu_json_path" > "$name/meshblu.json"
}

find_device_uuid() {
  local genisys_device_name="$1"
  local meshblu_json_path="$2"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output ".genisys.devices.$genisys_device_name.uuid"
}

main() {
  # Define args up here
  local meshblu_json_path

  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      # Arg with value
      # -x | --example)
      #   example="$value"
      #   shift
      #   ;;
      # Arg without value
      # -e | --example-flag)
      #   example_flag='true'
      #   ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$meshblu_json_path" ]; then
          meshblu_json_path="$param"
        # elif [ -z "$room_uuid"]; then
        #   room_uuid="$param"
        fi
        ;;
    esac
    shift
  done

  assert_required_params "$meshblu_json_path"
  assert_customer_json "$meshblu_json_path"

  find_hue_button_group "$meshblu_json_path" \
  && find_meeting_group "$meshblu_json_path" \
  && find_room_group "$meshblu_json_path" \
  && find_skype_group "$meshblu_json_path" \
  && find_user_group "$meshblu_json_path" \
  && find_endo_genisys_meetings "$meshblu_json_path" \
  && find_room_group_status "$meshblu_json_path" \
  && find_device "slurry-exchange-group" "slurryExchangeGroup" "$meshblu_json_path"

  exit $?
}

main "$@"
