#!/bin/bash

set -o pipefail
SCRIPT_NAME='find-connectors'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == $DEBUG ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_customer_json() {
  local meshblu_json_path="$1"
  local device_uuid="$(jq --raw-output '.uuid' "$meshblu_json_path")"
  local device_type="$(get_device_type "$meshblu_json_path" "$device_uuid")"

  if [ "$device_type" != "octoblu:smartspaces:customer" ]; then
    usage

    echo "meshblu.json must be a customer, however, I detected that it was a '$device_type'"
    exit 1
  fi
}

assert_required_params() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  if [ -n "$meshblu_json_path" -a -n "$room_uuid" ]; then
    return 0
  fi

  usage

  if [ -z "$meshblu_json_path" ]; then
    echo "Missing </path/to/customer/meshblu.json> argument"
  fi

  if [ -z "$room_uuid" ]; then
    echo "Missing <room-uuid> argument"
  fi

  exit 1
}

assert_room_uuid() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  local device_type="$(get_device_type "$meshblu_json_path" "$room_uuid")"

  if [ "$device_type" != "octoblu:smartspaces:room" ]; then
    usage

    echo "<room-uuid> must be a room, however, I detected that it was a '$device_type'"
    exit 1
  fi
}

get_device_type() {
  local meshblu_json_path="$1"
  local uuid="$2"

  local device="$(meshblu-util get --uuid "$uuid" "$meshblu_json_path")"
  local exit_code=$?
  if [ "$exit_code" != "0" ]; then
    return $exit_code
  fi

  echo -n "$device" | jq --raw-output '.type'
}

usage(){
  echo "USAGE: ${SCRIPT_NAME} </path/to/customer/meshblu.json> <room-uuid>"
  echo ''
  echo 'Description: ...'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help       print this help text'
  echo '  -v, --version    print the version'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

find_hue_button() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  local hue_button_uuid="$(find_hue_button_uuid "$meshblu_json_path" "$room_uuid")"
  local exit_code=$?
  if [ "$exit_code" != 0 ]; then
    return $exit_code
  fi

  mkdir -p hue-button \
  && meshblu-util generate-token --uuid "$hue_button_uuid" "$meshblu_json_path" > hue-button/meshblu.json
}

find_hue_button_uuid() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  meshblu-util get --uuid "$room_uuid" "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.hueButton.uuid'
}

find_hue_light() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  local hue_light_uuid="$(find_hue_light_uuid "$meshblu_json_path" "$room_uuid")"
  local exit_code=$?
  if [ "$exit_code" != 0 ]; then
    return $exit_code
  fi

  mkdir -p hue-light \
  && meshblu-util generate-token --uuid "$hue_light_uuid" "$meshblu_json_path" > hue-light/meshblu.json
}

find_hue_light_uuid() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  meshblu-util get --uuid "$room_uuid" "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.hueLight.uuid'
}

find_skype() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  local skype_uuid="$(find_skype_uuid "$meshblu_json_path" "$room_uuid")"
  local exit_code=$?
  if [ "$exit_code" != 0 ]; then
    return $exit_code
  fi

  mkdir -p skype \
  && meshblu-util generate-token --uuid "$skype_uuid" "$meshblu_json_path" > skype/meshblu.json
}

find_skype_uuid() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  meshblu-util get --uuid "$room_uuid" "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.skype.uuid'
}

find_endo_exchange() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  local endo_exchange_uuid="$(find_endo_exchange_uuid "$meshblu_json_path" "$room_uuid")"
  local exit_code=$?
  if [ "$exit_code" != 0 ]; then
    return $exit_code
  fi

  mkdir -p endo-exchange \
  && meshblu-util generate-token --uuid "$endo_exchange_uuid" "$meshblu_json_path" > endo-exchange/meshblu.json
}

find_endo_exchange_uuid() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  meshblu-util get --uuid "$room_uuid" "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.endoExchange.uuid'
}

find_slurry_exchange() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  local slurry_exchange_uuid="$(find_slurry_exchange_uuid "$meshblu_json_path" "$room_uuid")"
  local exit_code=$?
  if [ "$exit_code" != 0 ]; then
    return $exit_code
  fi

  mkdir -p slurry-exchange \
  && meshblu-util generate-token --uuid "$slurry_exchange_uuid" "$meshblu_json_path" > slurry-exchange/meshblu.json
}

find_slurry_exchange_uuid() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  meshblu-util get --uuid "$room_uuid" "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.slurryExchange.uuid'
}

find_exchange_sync() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  local exchange_sync_uuid="$(find_exchange_sync_uuid "$meshblu_json_path" "$room_uuid")"
  local exit_code=$?
  if [ "$exit_code" != 0 ]; then
    return $exit_code
  fi

  mkdir -p exchange-sync \
  && meshblu-util generate-token --uuid "$exchange_sync_uuid" "$meshblu_json_path" > exchange-sync/meshblu.json
}

find_exchange_sync_uuid() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  meshblu-util get --uuid "$room_uuid" "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.exchangeSync.uuid'
}

find_activities_device() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  local activities_device_uuid="$(find_activities_device_uuid "$meshblu_json_path" "$room_uuid")"
  local exit_code=$?
  if [ "$exit_code" != 0 ]; then
    return $exit_code
  fi

  mkdir -p activities-device \
  && meshblu-util generate-token --uuid "$activities_device_uuid" "$meshblu_json_path" > activities-device/meshblu.json
}

find_activities_device_uuid() {
  local meshblu_json_path="$1"
  local room_uuid="$2"

  meshblu-util get --uuid "$room_uuid" "$meshblu_json_path" \
  | jq --raw-output '.genisys.devices.activities.uuid'
}
main() {
  # Define args up here
  local meshblu_json_path
  local room_uuid

  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      # Arg with value
      # -x | --example)
      #   example="$value"
      #   shift
      #   ;;
      # Arg without value
      # -e | --example-flag)
      #   example_flag='true'
      #   ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$meshblu_json_path" ]; then
          meshblu_json_path="$param"
        elif [ -z "$room_uuid"]; then
          room_uuid="$param"
        fi
        ;;
    esac
    shift
  done

  assert_required_params "$meshblu_json_path" "$room_uuid"
  assert_customer_json "$meshblu_json_path"
  assert_room_uuid "$meshblu_json_path" "$room_uuid"

  find_hue_button "$meshblu_json_path" "$room_uuid" \
  && echo 'found hue button' \
  && find_hue_light "$meshblu_json_path" "$room_uuid" \
  && echo 'found hue light' \
  && find_skype "$meshblu_json_path" "$room_uuid" \
  && echo 'found skype' \
  && find_endo_exchange "$meshblu_json_path" "$room_uuid" \
  && echo 'found endo exchange' \
  && find_slurry_exchange "$meshblu_json_path" "$room_uuid" \
  && echo 'found slurry exchange' \
  && find_exchange_sync "$meshblu_json_path" "$room_uuid" \
  && echo 'found exchange sync' \
  && find_activities_device "$meshblu_json_path" "$room_uuid" \
  && echo 'found activities device'

  exit $?
}

main "$@"
