#!/bin/bash

set -o pipefail
SCRIPT_NAME='genisys-find-group-devices'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == "$DEBUG" ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_device_type() {
  local meshblu_json_path device device_type required_device_type
  meshblu_json_path="$1"
  required_device_type="$2"

  device="$(meshblu-util get "$meshblu_json_path")" || fatal "Could not retrieve device described at '$meshblu_json_path'"
  device_type="$(echo "$device" | jq --raw-output '.type')" || fatal "Could not parse device JSON returned from meshblu"

  if [ "$device_type" != "$required_device_type" ]; then
    err_echo "Device described at '$meshblu_json_path' must be '$required_device_type', received: '$device_type'"
    exit 1
  fi
}

assert_required_params() {
  local customer_meshblu_json_path="$1"

  if [ -n "$customer_meshblu_json_path" ] && [ -f "$customer_meshblu_json_path" ]; then
    return 0
  fi

  usage

  if [ -z "$customer_meshblu_json_path" ]; then
    echo "Missing </path/to/customer/meshblu.json> argument"
  elif [ ! -f "$meshblu_json_path" ]; then
    echo "Could not find a file at '$customer_meshblu_json_path'"
  fi

  exit 1
}

get_device_type() {
  local meshblu_json_path="$1"
  local uuid="$2"
  local device

  device="$(meshblu-util get --uuid "$uuid" "$meshblu_json_path")"
  local exit_code=$?
  if [ "$exit_code" != "0" ]; then
    return $exit_code
  fi

  echo -n "$device" | jq --raw-output '.type'
}

usage(){
  echo "USAGE:"
  echo "  ${SCRIPT_NAME} [OPTIONS] [/path/to/customer/meshblu.json]"
  echo ''
  echo "DESCRIPTION: "
  echo "  Find all devices enumerated in the customer's \"genisys.devices\""
  echo '  property. The device meshblu.jsons will each be placed in'
  echo '  the file: "/path/to/customer/../<name>/meshblu.json"'
  echo '  [/path/to/customer/meshblu.json] defaults to ./meshblu.json'
  echo ''
  echo 'OPTIONS:'
  echo '  -h, --help       print this help text'
  echo '  -v, --version    print the version'
  echo ''
  echo 'ENVIRONMENT:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory
  directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

find_device() {
  local genisys_device_name meshblu_json_path name device_dir device_uuid
  meshblu_json_path="$1"
  name="$2"
  genisys_device_name="$3"
  device_dir="$(dirname "$meshblu_json_path")/../$name"

  echo -n "| Updating $name... "
  device_uuid="$(find_device_uuid "$genisys_device_name" "$meshblu_json_path")"
  if [ -z "$device_uuid" ]; then
    echo "failed."
    return 1
  fi

  mkdir -p "$device_dir" \
  && meshblu-util generate-token --uuid "$device_uuid" "$meshblu_json_path" > "$device_dir/meshblu.json" \
  && echo "done." \
  || echo "failed."
}

find_device_uuid() {
  local genisys_device_name="$1"
  local meshblu_json_path="$2"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output ".genisys.devices.$genisys_device_name.uuid"
}

main() {
  local meshblu_json_path
  # Define args up here
  while [ "$1" != "" ]; do
    local param="$1"
    # local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$meshblu_json_path" ]; then
          meshblu_json_path="$param"
        # elif [ -z "$main_arg_2"]; then
        #   main_arg_2="$param"
        fi
        ;;
    esac
    shift
  done
  meshblu_json_path="${meshblu_json_path:-./meshblu.json}"

  assert_required_params "$meshblu_json_path"
  assert_device_type "$meshblu_json_path" "octoblu:smartspaces:customer"

  echo "Finding customer devices... "
  find_device "$meshblu_json_path" "slurry-exchange-group" "slurryExchangeGroup"
  find_device "$meshblu_json_path" "hue-button-group" "hueButtonGroup"
  find_device "$meshblu_json_path" "room-group" "roomGroup"
  find_device "$meshblu_json_path" "meeting-group" "meetingGroup"
  find_device "$meshblu_json_path" "skype-group" "skypeGroup"
  find_device "$meshblu_json_path" "user-group" "userGroup"
  find_device "$meshblu_json_path" "user-group-recruiter" "userGroupRecruiter"
  find_device "$meshblu_json_path" "endo-genisys-meetings" "meetingGroupEndoMeeting"
  find_device "$meshblu_json_path" "room-group-status" "roomGroupStatus"
  echo "done."
}

main "$@"
