#!/bin/bash

set -o pipefail
SCRIPT_NAME='find-group-devices'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == $DEBUG ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_required_params() {
  local meshblu_json_path="$1"

  if [ -n "$meshblu_json_path" ]; then
    return 0
  fi

  usage

  if [ -z "$meshblu_json_path" ]; then
    echo "Missing </path/to/customer/meshblu.json> argument"
  fi

  exit 1
}

get_device_type() {
  local meshblu_json_path="$1"
  local uuid="$2"
  local device

  device="$(meshblu-util get --uuid "$uuid" "$meshblu_json_path")"
  local exit_code=$?
  if [ "$exit_code" != "0" ]; then
    return $exit_code
  fi

  echo -n "$device" | jq --raw-output '.type'
}

usage(){
  echo "USAGE: ${SCRIPT_NAME} [/path/to/customer/meshblu.json]"
  echo ''
  echo 'Description: ...'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help       print this help text'
  echo '  -v, --version    print the version'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

find_device() {
  local name="$1"
  local genisys_device_name="$2"
  local meshblu_json_path="./customer/meshblu.json"

  echo -n "| Updating $name... "
  local device_uuid="$(find_device_uuid "$genisys_device_name" "$meshblu_json_path")"
  if [ -z "$device_uuid" ]; then
    echo "failed."
    return 1
  fi

  mkdir -p "$name" \
  && meshblu-util generate-token --uuid "$device_uuid" "$meshblu_json_path" > "$name/meshblu.json" \
  && echo "done." \
  || echo "failed."
}

find_device_uuid() {
  local genisys_device_name="$1"
  local meshblu_json_path="$2"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output ".genisys.devices.$genisys_device_name.uuid"
}

main() {
  # Define args up here
  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        ;;
    esac
    shift
  done

  if [ ! -f "./customer/meshblu.json" ]; then
    panic "Error: ./customer/meshblu.json not found"
  fi

  echo "Finding customer devices... "
  find_device "slurry-exchange-group" "slurryExchangeGroup"
  find_device "hue-button-group" "hueButtonGroup"
  find_device "room-group" "roomGroup"
  find_device "meeting-group" "meetingGroup"
  find_device "skype-group" "skypeGroup"
  find_device "user-group" "userGroup"
  find_device "user-group-recruiter" "userGroupRecruiter"
  find_device "endo-genisys-meetings" "meetingGroupEndoMeeting"
  find_device "room-group-status" "roomGroupStatus"
  echo "done."
}

main "$@"
