#!/bin/bash

set -o pipefail
SCRIPT_NAME='update-connector-versions'
TMP_JSON="/tmp/$(date +%s)-$(( ( RANDOM % 999999999 )  + 1 )).json"

# We are deliberatly locking the filename down now
# shellcheck disable=SC2064
trap "rm -f $TMP_JSON; exit" INT TERM EXIT

usage(){
  echo "USAGE: ${SCRIPT_NAME} </path/to/room>"
  echo ''
  echo 'Description: ...'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help       print this help text'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}

find_uuid() {
  local meshblu_json_path="$1"
  cat "$meshblu_json_path" | jq --raw-output '.uuid'
}

find_token() {
  local meshblu_json_path="$1"
  cat "$meshblu_json_path" | jq --raw-output '.token'
}

find_repo() {
  local meshblu_json_path="$1"
  meshblu-util get "$meshblu_json_path" >$TMP_JSON; jq -r '.connector' <$TMP_JSON
}

find_latest_version() {
  #/releases/:owner/:repo/:version/version/resolve
  local meshblu_json_path repo uuid token
  meshblu_json_path="$1"
  repo=$(find_repo "$meshblu_json_path")
  uuid=$(find_uuid "$meshblu_json_path")
  token=$(find_token "$meshblu_json_path")
  curl -s https://$uuid:$token@connector-service.octoblu.com/releases/octoblu/$repo/latest/version/resolve | jq -r '.version' | sed -e 's|^v||'
}

update_latest_version() {
  local current meshblu_json_path version
  meshblu_json_path="$1"
  version=$(find_latest_version "$meshblu_json_path")
  current=$(meshblu-util get "$meshblu_json_path" >$TMP_JSON; jq -r '.connectorMetadata.currentVersion' <$TMP_JSON | sed -e 's|^v||')
  if [ "$current" != "$version" ]; then
    echo "updating $meshblu_json_path from $current to $version"
    meshblu-util update -p -d '{"$set": {"connectorMetadata.version": "'$version'"}}' "$meshblu_json_path"
  fi
}

assert_required_params() {
  local meshblu_json_path="$1"

  if [ -n "$meshblu_json_path" ]; then
    return 0
  fi

  usage

  if [ -z "$meshblu_json_path" ]; then
    echo "Missing [/path/to/meshblu.json] argument"
  fi

  exit 1
}

upgrade_path() {
  local meshblu_json_paths meshblu_root
  meshblu_root="$1"

  meshblu_json_paths=( $(find "$meshblu_root" -iname meshblu.json) )
  for meshblu_json_path in "${meshblu_json_paths[@]}"; do
    local connector
    connector="$(meshblu-util get "$meshblu_json_path" >$TMP_JSON 2>/dev/null; jq -r '.connector' <$TMP_JSON)"

    if [[ -n "$connector" ]] && [[ "$connector" != "null" ]]; then
      assert_required_params "$meshblu_json_path"
      update_latest_version "$meshblu_json_path"
    fi
  done
}

main() {
  # Define args up here
  local meshblu_root

  while [ "$1" != "" ]; do
    local param="$1"
    # local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$meshblu_root" ]; then
          meshblu_root="$param"
        fi
        ;;
    esac
    shift
  done

  genisys-find-rooms

  if [ "$meshblu_root" == "" ]; then
    meshblu_root='./rooms'
  fi

  upgrade_path $meshblu_root
  exit $?
}

main "$@"
