#!/bin/bash

SCRIPT_NAME='genisys-create-customer'
DEFAULT_CONFIGURATION_URL='https://raw.githubusercontent.com/octoblu/smartspaces-bootstrap-configuration/master/semi-stable.json'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == "$DEBUG" ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

err_echo() {
  local message="$1"
  echo "$message" 1>&2
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_required_env() {
  if [ -n "$GENISYS_ATHENA_ADMIN_USERNAME" ] && [ -n "$GENISYS_ATHENA_ADMIN_PASSWORD" ]; then
    return 0
  fi

  usage 1>&2

  err_echo ""
  if [ -z "$GENISYS_ATHENA_ADMIN_USERNAME" ]; then
    err_echo "missing required env GENISYS_ATHENA_ADMIN_USERNAME"
  fi

  if [ -z "$GENISYS_ATHENA_ADMIN_PASSWORD" ]; then
    err_echo "missing required env GENISYS_ATHENA_ADMIN_PASSWORD"
  fi

  err_echo ""
  err_echo "** when-in-doubt update dotfiles **"
  err_echo ""

  exit 1
}

assert_required_params() {
  local configuration_url="$1"
  local domain="$2"
  local name="$3"
  local meshblu_json_path="$4"

  if [ -n "$configuration_url" ] && [ -n "$domain" ] && [ -n "$name" ] && [ -n "$meshblu_json_path" ] && [ -f "$meshblu_json_path" ]; then
    return 0
  fi

  usage 1>&2

  if [ -z "$configuration_url" ]; then
    err_echo "Missing -c, --configuration-url argument"
  fi

  if [ -z "$domain" ]; then
    err_echo "Missing -d, --domain argument"
  fi

  if [ -z "$name" ]; then
    err_echo "Missing -n, --name argument"
  fi

  if [ -z "$meshblu_json_path" ]; then
    err_echo "Missing </path/to/meshblu.json> argument"
  elif [ -z "$meshblu_json_path" ]; then
    err_echo "</path/to/meshblu.json> doesn't seem to be a file"
  fi

  exit 1
}

assert_required_auth_params() {
  local auth_type="$1"
  local tenate_id="$2"
  case "$auth_type" in
    citrix)
      debug "using auth-type citrix"
      ;;
    azure)
      debug "using auth-type azure"
      if [ -z "$tenate_id" ]; then
        usage 1>&2
        err_echo "auth-type of azure must include a tenate-id"
        exit 1
      fi
      ;;
    other)
      debug "using auth-type other"
      ;;
    *)
      usage 1>&2
      err_echo 'auth-type must be one of "citrix", "azure", "other"'
      exit 1
  esac
}

usage(){
  echo "USAGE: ${SCRIPT_NAME} [OPTIONS] </path/to/super-user/meshblu.json>"
  echo ''
  echo 'DESCRIPTION: Will register a new customer with the genisys-factory service'
  echo '             and outputs the resulting meshblu.json as stdout'
  echo ''
  echo 'EXAMPLE:'
  echo "  ${SCRIPT_NAME} ./super-user/meshblu.json > customers/ctxs/customer/meshblu.json"
  echo ''
  echo ''
  echo 'OPTIONS:'
  echo '  -c, --configuration-url  Configuration URL that contains the rulesets'
  echo "                           (default: \"$DEFAULT_CONFIGURATION_URL\")"
  echo '  -d, --domain             Domain where the customer services will run (ex: "cbn.octo.space")'
  echo '  -a, --auth-type          Type of authentication to use (must be one of "citrix", "azure", "none")'
  echo '  -t, --tenate-id          Tenate ID for Azure AD (required for authentication type of "azure")'
  echo '  -h, --help               Print this help text'
  echo '  -n, --name               Human readable name (ex: "Cyberdyne Systems")'
  echo '  -v, --version            Print the version'
  echo ''
  echo 'ENVIRONMENT:'
  echo '  GENISYS_ATHENA_ADMIN_USERNAME   (required) Athena Auth Service Admin Username'
  echo '  GENISYS_ATHENA_ADMIN_PASSWORD   (required) Athena Auth Service Admin Password'
  echo '  DEBUG                           print debug output'
  echo ''
}

version(){
  local directory
  directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

create_customer(){
  local configuration_url="$1"
  local domain="$2"
  local name="$3"
  local uuid="$4"
  local token="$5"

  curl \
    --user "$uuid:$token" \
    --data "{\"name\": \"$name\", \"domain\": \"$domain\", \"configurationUrl\": \"$configuration_url\"}" \
    --header 'Content-Type: application/json' \
    --fail \
    -X POST \
    "https://factory-service.ctxs.octo.space/v2/customers"
}

create_athena_customer() {
  local auth_type="$1"
  local tenate_id="$2"
  local domain="$3"
  local name="$4"
  case "$auth_type" in
    citrix)
      curl \
        --user "$GENISYS_ATHENA_ADMIN_USERNAME:$GENISYS_ATHENA_ADMIN_PASSWORD" \
        --data "{\"name\": \"$name\", \"domain\": \"$domain\"}" \
        --header 'Content-Type: application/json' \
        --fail \
        -X POST \
        "https://athena.smart.octo.space/customers/citrix"
      ;;
    azure)
      curl \
        --user "$GENISYS_ATHENA_ADMIN_USERNAME:$GENISYS_ATHENA_ADMIN_PASSWORD" \
        --data "{\"name\": \"$name\", \"domain\": \"$domain\", \"tenantId\": \"$tenate_id\"}" \
        --header 'Content-Type: application/json' \
        --fail \
        -X POST \
        "https://athena.smart.octo.space/customers/azure"
      ;;
  esac
}

main() {
  local configuration_url domain meshblu_json_path name auth_type tenate_id
  configuration_url="$DEFAULT_CONFIGURATION_URL"

  # Define args up here
  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -c | --configuration-url)
        configuration_url="$value"
        shift
        ;;
      -d | --domain)
        domain="$value"
        shift
        ;;
      -a | --auth-type)
        auth_type="$value"
        shift
        ;;
      -t | --tenate-id)
        tenate_id="$value"
        shift
        ;;
      -h | --help)
        usage
        exit 0
        ;;
      -n | --name)
        name="$value"
        shift
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        if [ -z "$meshblu_json_path" ]; then
          meshblu_json_path="$param"
        fi
        ;;
    esac
    shift
  done

  assert_required_env
  assert_required_params "$configuration_url" "$domain" "$name" "$meshblu_json_path"
  assert_required_auth_params "$auth_type" "$tenate_id"


  uuid="$(jq --raw-output '.uuid' "$meshblu_json_path")"
  token="$(jq --raw-output '.token' "$meshblu_json_path")"

  create_customer "$configuration_url" "$domain" "$name" "$uuid" "$token"
  create_athena_customer "$auth_type" "$tenate_id" "$domain" "$name"
}

main "$@"
