#!/bin/bash

SCRIPT_NAME='genisys-bootstrap-customer'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == "$DEBUG" ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_required_params() {
  local subdomain="$1"

  if [ -n "$subdomain" ]; then
    return 0
  fi

  usage

  if [ -z "$subdomain" ]; then
    echo "Missing subdomain argument"
  fi

  exit 1
}

usage(){
  echo "USAGE: ${SCRIPT_NAME}"
  echo ''
  echo 'Description: ...'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help       print this help text'
  echo '  -v, --version    print the version'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory
  directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

panic(){
  local message="$1"
  echo "$message"
  exit 1
}

main() {
  local subdomain customerUuid customerToken roomUuid
  # Define args up here
  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      -s | --subdomain)
        subdomain="$value"
        shift
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        ;;
    esac
    shift
  done

  assert_required_params "$subdomain"

  if [ ! -f "./customer/meshblu.json" ]; then
    panic "Error: ./customer/meshblu.json not found"
  fi

  customerUuid="$(jq -r '.uuid' ./customer/meshblu.json)"
  customerToken="$(jq -r '.token' ./customer/meshblu.json)"

  if [ "$customerUuid" == "" ]; then
    panic "Error: customer uuid not found"
  fi

  if [ "$customerToken" == "" ]; then
    panic "Error: customer token not found"
  fi

  genisys-find-rooms

  for room in rooms/*; do
    echo -n "Updating $room... "
    roomUuid="$(jq -r '.uuid' ./$room/meshblu.json)"

    if [ "$roomUuid" == "" ]; then
      panic "Error: room uuid not found"
    fi


    curl --fail \
      -H 'Content-Type: application/json'\
      -X PATCH "https://$customerUuid:$customerToken@factory-service.$subdomain.octo.space/v2/spaces/$roomUuid" \
    && curl --fail \
      -H 'Content-Type: application/json'\
      -X PATCH "https://$customerUuid:$customerToken@factory-service.$subdomain.octo.space/v2/spaces/exchange" \
      -d "{\"roomId\": \"$roomUuid\"}" \
    && echo "done." \
    || echo "failed."
  done
}

main "$@"
