#!/bin/bash

SCRIPT_NAME='genisys-create-customer'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == "$DEBUG" ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_required_params() {
  local configuration_url="$1"
  local domain="$2"
  local name="$3"
  local meshblu_json_path="$4"

  if [ -n "$configuration_url" ] && [ -n "$domain" ] && [ -n "$name" ] && [ -n "$meshblu_json_path" ] && [ -f "$meshblu_json_path" ]; then
    return 0
  fi

  usage

  if [ -z "$configuration_url" ]; then
    echo "Missing -c, --configuration-url argument"
  fi

  if [ -z "$domain" ]; then
    echo "Missing -d, --domain argument"
  fi

  if [ -z "$name" ]; then
    echo "Missing -n, --name argument"
  fi

  if [ -z "$meshblu_json_path" ]; then
    echo "Missing </path/to/meshblu.json> argument"
  elif [ -z "$meshblu_json_path" ]; then
    echo "</path/to/meshblu.json> doesn't seem to be a file"
  fi

  exit 1
}

usage(){
  echo "USAGE: ${SCRIPT_NAME} </path/to/super-user/meshblu.json>"
  echo ''
  echo 'DESCRIPTION: Will register a new customer with the genisys-factory service'
  echo '             and outputs the resulting meshblu.json as stdout'
  echo ''
  echo 'EXAMPLE:'
  echo "  ${SCRIPT_NAME} ./super-user/meshblu.json > customers/ctxs/customer/meshblu.json"
  echo ''
  echo ''
  echo 'ARGUMENTS:'
  echo '  -c, --configuration-url  Configuration URL that contains the rulesets (ex: "https://raw.githubusercontent.com/octoblu/smartspaces-bootstrap-configuration/master/semi-stable.json")'
  echo '  -d, --domain             Domain where the customer services will run (ex: "cbn.octo.space")'
  echo '  -h, --help               Print this help text'
  echo '  -n, --name               Human readable name (ex: "Cyberdyne Systems")'
  echo '  -v, --version            Print the version'
  echo ''
  echo 'ENVIRONMENT:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory
  directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

create_customer(){
  local configuration_url="$1"
  local domain="$2"
  local name="$3"
  local uuid="$4"
  local token="$4"

  curl \
    --data "{\"name\": \"$name\", \"domain\": \"$domain\", \"configurationUrl\": \"$configuration_url\"}" \
    --header 'Content-Type: application/json' \
    --verbose \
    --fail \
    -X POST \
    "https://$uuid:$token@factory-service.thinclient.octo.space/v2/customers"
}

main() {
  local configuration_url domain meshblu_json_path name

  # Define args up here
  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -c | --configuration-url)
        configuration_url="$value"
        shift
        ;;
      -d | --domain)
        domain="$value"
        shift
        ;;
      -h | --help)
        usage
        exit 0
        ;;
      -n | --name)
        name="$value"
        shift
        ;;
      -v | --version)
        version
        exit 0
        ;;
      # Arg with value
      # -x | --example)
      #   example="$value"
      #   shift
      #   ;;
      # Arg without value
      # -e | --example-flag)
      #   example_flag='true'
      #   ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$meshblu_json_path" ]; then
          meshblu_json_path="$param"
        # elif [ -z "$main_arg_2"]; then
        #   main_arg_2="$param"
        fi
        ;;
    esac
    shift
  done

  assert_required_params "$configuration_url" "$domain" "$name" "$meshblu_json_path"

  uuid="$(jq --raw-output '.uuid' "$meshblu_json_path")"
  token="$(jq --raw-output '.token' "$meshblu_json_path")"

  create_customer "$configuration_url" "$domain" "$name" "$uuid" "$token"
}

main "$@"
