#!/bin/bash

set -o pipefail
SCRIPT_NAME='genisys-find-room-devices'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == "$DEBUG" ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$*"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

echo_error_red() {
  local red='\033[0;31m'
  local no_color='\033[0;0m'
  local message="$*"

  (>&2 echo -e "${red}$message${no_color}")
}

fatal() {
  local message="$@"
  echo_error_red "$message"
  exit 1
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_customer_json() {
  local customer_uuid device_type customer_json_path room_uuid

  customer_json_path="$1"
  room_uuid="$2"

  if [ ! -f "$customer_json_path" ]; then
    usage && fatal "</path/to/room/../../customer/meshblu.json> does not seem to point to a file"
  fi

  customer_uuid="$(jq --raw-output '.uuid' "$customer_json_path")"
  if [ "$?" != "0" ]; then
    usage && fatal "the file at </path/to/room/../../customer/meshblu.json> does not seem to be JSON"
  fi
  if [ -z "$customer_uuid" ]; then
    usage && fatal "the file at </path/to/room/../../customer/meshblu.json> was valid JSON, but did not contain a uuid"
  fi

  device_type="$(get_device_type "$customer_json_path" "$customer_uuid")"
  if [ "$?" != "0" ]; then
    usage && fatal "could not retrieve device for </path/to/room/../../customer/meshblu.json>"
  fi

  if [ "$device_type" != "octoblu:smartspaces:customer" ]; then
    usage && fatal "device in </path/to/room/../../customer/meshblu.json> must be of type 'octoblu:smartspaces:customer', however, it seems to be a '$device_type'"
  fi

  get_device_type "$customer_json_path" "$room_uuid" > /dev/null
  if [ "$?" != "0" ]; then
    usage && fatal "device in </path/to/room/../../customer/meshblu.json> could not retrieve the </path/to/room/meshblu.json> device"
  fi
}

assert_required_params() {
  local room_json_path="$1"

  if [ -n "$room_json_path" ]; then
    return 0
  fi

  usage

  if [ -z "$room_json_path" ]; then
    echo_error_red "Missing </path/to/room/meshblu.json> argument"
  fi

  exit 1
}

assert_room_json() {
  local device_type meshblu_json_path uuid

  meshblu_json_path="$1"
  if [ ! -f "$meshblu_json_path" ]; then
    usage && fatal "</path/to/room/meshblu.json> does not seem to point to a file"
  fi

  uuid="$(jq --raw-output '.uuid' "$meshblu_json_path")"
  if [ "$?" != "0" ]; then
    usage && fatal "the file at </path/to/room/meshblu.json> does not seem to be JSON"
  fi
  if [ -z "$uuid" ]; then
    usage && fatal "the file at </path/to/room/meshblu.json> was valid JSON, but did not contain a uuid"
  fi

  device_type="$(get_device_type "$meshblu_json_path" "$uuid")"
  if [ "$?" != "0" ]; then
    usage && fatal "could not retrieve device for </path/to/room/meshblu.json>"
  fi

  if [ "$device_type" != "octoblu:smartspaces:room" ]; then
    usage && fatal "device in </path/to/room/meshblu.json> must be of type 'octoblu:smartspaces:room', however, it seems to be a '$device_type'"
  fi
}

get_customer_json_path() {
  local room_json_path="$1"
  debug "get_customer_json_path: '$room_json_path'"
  echo "$(dirname "$room_json_path")/../../customer/meshblu.json"
}

get_device() {
  local tmpfile meshblu_json_path uuid
  meshblu_json_path="$1"
  uuid="$2"
  tmpfile="$(mktemp)"
  meshblu-util get --uuid "$uuid" "$meshblu_json_path" \
    > "$tmpfile" && cat "$tmpfile"
}

get_device_type() {
  local device exit_code meshblu_json_path uuid

  meshblu_json_path="$1"
  uuid="$2"

  debug "get_device_type: '$meshblu_json_path' '$uuid'"

  device="$(get_device "$meshblu_json_path" "$uuid")"
  exit_code=$?

  if [ "$exit_code" != "0" ]; then
    return $exit_code
  fi

  echo -n "$device" | jq --raw-output '.type'
}

get_room_uuid() {
  local room_json_path="$1"
  debug "get_room_uuid: '$room_json_path'"

  jq --raw-output '.uuid' "$room_json_path"
}

usage(){
  echo "USAGE: ${SCRIPT_NAME} </path/to/room/meshblu.json>"
  echo ''
  echo 'Description: Will create a meshblu.json for all genisys devices in the room'
  echo '             in the directory: /path/to/room/<device>/meshblu.json'
  echo ''
  echo '             Will currently find endo-exchange, slurry-exchange, hue-button,'
  echo '             hue-light, powermate, skype, and windows-citrix-receiver'
  echo ''
  echo "             NOTE: this script expects the customer's meshblu.json to be"
  echo '             located at /path/to/room/../../customer/meshblu.json'
  echo 'Arguments:'
  echo '  -h, --help       print this help text'
  echo '  -v, --version    print the version'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory
  directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

find_device() {
  local customer_json_path device_key folder_name room_json_path room_path

  customer_json_path="$1"
  room_json_path="$2"
  device_key="$3"
  folder_name="$4"

  debug "find_device: '$customer_json_path' '$room_json_path' '$device_key' '$folder_name'"

  room_path="$(dirname "$room_json_path")" \
  && room_uuid="$(get_room_uuid "$room_json_path")" \
  && device_uuid="$(find_device_uuid "$customer_json_path" "$room_uuid" "$device_key")" \
  && mkdir -p "$room_path/$folder_name" \
  && meshblu-util generate-token --uuid "$device_uuid" "$customer_json_path" > "$room_path/$folder_name/meshblu.json" 2>/dev/null
}

find_device_uuid() {
  local customer_json_path="$1"
  local room_uuid="$2"
  local device_key="$3"

  debug "find_device_uuid: '$customer_json_path' '$room_uuid' '$device_key'"

  get_device "$customer_json_path" "$room_uuid" \
  | jq --raw-output ".genisys.devices.$device_key.uuid"
}

main() {
  # Define args up here
  local room_json_path

  while [ "$1" != "" ]; do
    local param="$1"
    # local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      # Arg with value
      # -x | --example)
      #   example="$value"
      #   shift
      #   ;;
      # Arg without value
      # -e | --example-flag)
      #   example_flag='true'
      #   ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$room_json_path" ]; then
          room_json_path="$param"
        fi
        ;;
    esac
    shift
  done

  local customer_json_path room_uuid

  assert_required_params "$room_json_path"
  assert_room_json "$room_json_path"

  customer_json_path="$(get_customer_json_path "$room_json_path")" || fatal "Could not find customer_json_path"
  room_uuid="$(get_room_uuid "$room_json_path")" || fatal "Could not find room_uuid"

  assert_customer_json "$customer_json_path" "$room_uuid"

  local failed_devices=()

  find_device "$customer_json_path" "$room_json_path" "endoExchange" "endo-exchange" || failed_devices+=("endo-exchange")
  find_device "$customer_json_path" "$room_json_path" "slurryExchange" "slurry-exchange" || failed_devices+=("slurry-exchange")
  find_device "$customer_json_path" "$room_json_path" "powermate" "powermate" || failed_devices+=("powermate")
  find_device "$customer_json_path" "$room_json_path" "skype" "skype" || failed_devices+=("skype")
  find_device "$customer_json_path" "$room_json_path" "windowsCitrixReceiver" "windows-citrix-receiver" || failed_devices+=("windows-citrix-receiver")
  find_device "$customer_json_path" "$room_json_path" "linuxCitrixReceiver" "linux-citrix-receiver" || failed_devices+=("linux-citrix-receiver")

  if [ "${#failed_devices[@]}" != "0" ]; then
    fatal "Could not generate a meshblu.json for these devices: ${failed_devices[*]}"
  fi
}

main "$@"
