#!/bin/bash

SCRIPT_NAME='genisys-create-admin'

set -o pipefail

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == "$DEBUG" ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_is_customer() {
  local meshblu_json_path device device_type
  meshblu_json_path="$1"

  device="$(meshblu-util get "$meshblu_json_path")" || fatal "Could not retrieve device described at </path/to/customer/meshblu.json>"
  device_type="$(echo "$device" | jq --raw-output '.type')" || fatal "Could not parse device JSON returned from meshblu"

  if [ "$device_type" != "octoblu:smartspaces:customer" ]; then
    fatal "Device described at </path/to/customer/meshblu.json> must be 'octoblu:smartspaces:customer', received: '$device_type'"
  fi
}

assert_required_params() {
  local email="$1"
  local password="$2"
  local meshblu_json_path="$3"

  if [ -n "$email" ] && [ -n "$password" ] && [ -n "$meshblu_json_path" ] && [ -f "$meshblu_json_path" ]; then
    return 0
  fi

  usage

  if [ -z "$email" ]; then
    echo "Missing -e, --email argument"
  fi

  if [ -z "$password" ]; then
    echo "Missing -p, --password argument"
  fi

  if [ -z "$meshblu_json_path" ]; then
    echo "Missing </path/to/customer/meshblu.json> argument"
  elif [ -z "$meshblu_json_path" ]; then
    echo "</path/to/customer/meshblu.json> doesn't seem to be a file"
  fi

  exit 1
}

fatal(){
  local message="$1"
  echo "$message" 1>&2
  exit 1
}

usage(){
  echo "USAGE: ${SCRIPT_NAME} </path/to/customer/meshblu.json>"
  echo ''
  echo 'Description: Will create a new admin account for the given customer.'
  echo "             The account's domain will be retrieved from the customer"
  echo '             device.'
  echo ''
  echo 'Arguments:'
  echo '  -d, --domain     overrides the domain from the customer device'
  echo '  -e, --email      the desired email address for the new admin account'
  echo '  -h, --help       print this help text'
  echo '  -p, --password   the desired login password for the new admin account'
  echo '  -v, --version    print the version'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory
  directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

create_admin_account() {
  local customer_token customer_uuid domain email meshblu_json_path password
  email="$1"
  password="$2"
  meshblu_json_path="$3"
  domain="$4"

  customer_uuid="$(jq --raw-output '.uuid' "$meshblu_json_path")" || fatal "could not get uuid for customer"
  customer_token="$(jq --raw-output '.token' "$meshblu_json_path")" || fatal "could not get token for customer"

  if [ -z "$domain" ]; then
    domain="$(get_domain "$meshblu_json_path")" || fatal "could not retrieve domain"
  fi

  post_new_admin "$customer_uuid" "$customer_token" "$domain" "$email" "$password" \
  && echo "" \
  && echo "Account Created." \
  && echo "You should now be able to login at https://admin.$domain"
}


get_domain(){
  local meshblu_json_path="$1"

  meshblu-util get "$meshblu_json_path" \
  | jq --raw-output '.genisys.domain'
}

post_new_admin(){
  local customer_token customer_uuid domain email password

  customer_uuid="$1"
  customer_token="$2"
  domain="$3"
  email="$4"
  password="$5"

  curl \
    --fail \
    -X POST \
    --user "$customer_uuid:$customer_token" \
    --header 'Content-Type: application/json' \
    --data "{\"domain\":\"$domain\",\"email\":\"$email\",\"password\":\"$password\"}" \
    https://admin-authenticator.smart.octo.space/users
}

main() {
  local domain email meshblu_json_path password

  # Define args up here
  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -d | --domain)
        domain="$value"
        shift
        ;;
      -e | --email)
        email="$value"
        shift
        ;;
      -h | --help)
        usage
        exit 0
        ;;
      -p | --password)
        password="$value"
        shift
        ;;
      -v | --version)
        version
        exit 0
        ;;
      # Arg with value
      # -x | --example)
      #   example="$value"
      #   shift
      #   ;;
      # Arg without value
      # -e | --example-flag)
      #   example_flag='true'
      #   ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$meshblu_json_path" ]; then
          meshblu_json_path="$param"
        # elif [ -z "$main_arg_2"]; then
        #   main_arg_2="$param"
        fi
        ;;
    esac
    shift
  done

  assert_required_params "$email" "$password" "$meshblu_json_path"
  assert_is_customer "$meshblu_json_path"

  create_admin_account "$email" "$password" "$meshblu_json_path" "$domain"
}

main "$@"
