#!/bin/bash

set -e -o pipefail

SCRIPT_NAME='genisys-setup-linux-citrix-receiver'
CACHE_DIR="$(mktemp -d)"

assert_required_params() {
  local meshblu_json_path room_uuid domain name password storefront_url xd_type username errors

  meshblu_json_path="$1"
  room_uuid="$2"
  domain="$3"
  name="$4"
  password="$5"
  storefront_url="$6"
  xd_type="$7"
  username="$8"

  errors=()

  if [ -z "$meshblu_json_path" ]; then
    errors+=('Missing <path/to/customer/meshblu.json>')
  elif [ ! -f "$meshblu_json_path" ]; then
    errors+=("Does not seem to be a file: '$meshblu_json_path'")
  elif ! get_device "$meshblu_json_path" > /dev/null; then
    errors+=("Could not retrieve device at: '$meshblu_json_path'")
  elif [ "$(get_device_type "$meshblu_json_path")" != "octoblu:smartspaces:customer" ]; then
    errors+=("Device at '$meshblu_json_path' device was not of type 'octoblu:smartspaces:customer', was '$(get_device_type "$meshblu_json_path")'")
  fi

  if [ -z "$domain" ]; then
    errors+=('Missing required argument: -d, --domain')
  fi

  if [ -z "$name" ]; then
    errors+=('Missing required argument: -n, --name')
  fi

  if [ -z "$password" ]; then
    errors+=('Missing required argument: -p, --password')
  fi

  if [ -z "$room_uuid" ]; then
    errors+=('Missing required argument: -r, --room-uuid')
  elif ! get_device "$meshblu_json_path" "$room_uuid" > /dev/null; then
    errors+=("Could not retrieve room device with uuid: '$room_uuid'")
  elif [ "$(get_device_type "$meshblu_json_path" "$room_uuid")" != "octoblu:smartspaces:room" ]; then
    errors+=("Device with uuid '$room_uuid' device was not of type 'octoblu:smartspaces:room', was '$(get_device_type "$meshblu_json_path" "$room_uuid")'")
  fi

  if [ -z "$storefront_url" ]; then
    errors+=('Missing required argument: -s, --storefront-url')
  fi

  if [ -z "$xd_type" ]; then
    errors+=('Missing required argument: -t, --type')
  fi

  if [ -z "$username" ]; then
    errors+=('Missing required argument: -u, --username')
  fi

  if [ ${#errors[@]} -eq 0 ]; then
    return 0
  fi

  usage 1>&2
  for error in "${errors[@]}"; do
    err_echo "$error"
  done
  exit 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

err_echo() {
  echo "$@" 1>&2
}

fatal() {
  err_echo "$@"
  exit 1
}

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  # shellcheck disable=2053
  if [[ $SCRIPT_NAME == $DEBUG ]]; then
    return 0
  fi
  return 1
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

usage(){
  echo 'USAGE: '
  echo "  ${SCRIPT_NAME} [OPTIONS] <path/to/customer/meshblu.json>"
  echo ''
  echo 'DESCRIPTION:'
  echo '  Will find the linux-citrix-receiver device and'
  echo '  update the configuration needed to have it auto'
  echo '  login to XenDesktop.'
  echo ''
  echo 'OPTIONS:'
  echo '  -h, --help            print this help text'
  echo '  -v, --version         print the version'
  echo '  -d, --domain          linux domain for XenDesktop'
  echo '                        (default: "CITRITE")'
  echo '  -n, --name            name of the linux XenDesktop instance '
  echo '                        (default "Smart Spaces POC - Server 2016")'
  echo '  -p, --password        password for XenDesktop'
  echo '  -r, --room-uuid       uuid of the room to update'
  echo '  -s, --storefront-url  url to the XenDesktop storefront'
  echo '                        (default: "https://alpha.xendesktop.eng.citrite.net/Citrix/ExternalWeb")'
  echo '  -t, --type            XenDesktop type'
  echo '                        (default: "Citrix.MPS.Desktop")'
  echo '  -u, --username        username for XenDesktop'
  echo ''
  echo 'ENVIRONMENT:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory
  directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

get_device() {
  local cache_filename meshblu_json_path uuid
  meshblu_json_path="$1"
  uuid="$2"

  if [ -z "$uuid" ]; then
    uuid="$(jq --raw-output '.uuid' "$meshblu_json_path")"
  fi

  cache_filename="$CACHE_DIR/$uuid.json"

  if [ ! -f "$cache_filename" ]; then
    get_device_nocache "$meshblu_json_path" "$uuid" > "$cache_filename"
  fi

  cat "$cache_filename"
}

get_device_nocache() {
  local meshblu_json_path uuid

  meshblu_json_path="$1"
  uuid="$2"

  meshblu-util get --uuid "$uuid" "$meshblu_json_path"
}

get_device_type() {
  set -e -o pipefail

  local meshblu_json_path uuid
  meshblu_json_path="$1"
  uuid="$2"

  get_device "$meshblu_json_path" "$uuid" | jq --raw-output '.type'
}

get_linux_citrix_receiver_uuid() {
  local meshblu_json_path room_uuid linux_citrix_receiver_uuid
  meshblu_json_path="$1"
  room_uuid="$2"

  linux_citrix_receiver_uuid="$(get_device "$meshblu_json_path" "$room_uuid" | jq --raw-output '.genisys.devices.linuxCitrixReceiver.uuid')" || return 1

  if [ -z "$linux_citrix_receiver_uuid" ] || [ "$linux_citrix_receiver_uuid" == "null" ]; then
    err_echo "Could not find linuxCitrixReceiver in .genisys.devices: '$(get_device "$meshblu_json_path" "$room_uuid" | jq --raw-output '.genisys.devices')'"
    return 1
  fi

  echo -n "$linux_citrix_receiver_uuid"
}

run() {
  local meshblu_json_path room_uuid domain name password storefront_url xd_type username

  meshblu_json_path="$1"
  room_uuid="$2"
  domain="$3"
  name="$4"
  password="$5"
  storefront_url="$6"
  xd_type="$7"
  username="$8"

  linux_citrix_receiver_uuid="$(get_linux_citrix_receiver_uuid "$meshblu_json_path" "$room_uuid")" || return 1

  update_json="$(jq \
    --null-input \
    --arg domain "$domain" \
    --arg name "$name" \
    --arg xdType "$xd_type" \
    --arg username "$username" \
    --arg password "$password" \
    --arg storefrontUrl "$storefront_url" \
    '{
      "$set": {
        "options": {
          "domain": $domain,
          "query": {
            "name": $name,
            "type": $xdType
          },
          "username": $username,
          "password": $password,
          "storeFrontUrl": $storefrontUrl
        }
      }
    }
  ')" || return 1

  meshblu-util update --uuid "$linux_citrix_receiver_uuid" --put --data "$update_json" "$meshblu_json_path"
}

main() {
  # Define args up here
  while [ "$1" != "" ]; do
    local param value meshblu_json_path domain name password storefront_url xd_type username room_uuid
    param="$1"
    # shellcheck disable=2034
    value="$2"

    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      -d | --domain)
        domain="$value"
        shift
        ;;
      -n | --name)
        name="$value"
        shift
        ;;
      -p | --password)
        password="$value"
        shift
        ;;
      -r | --room-uuid)
        room_uuid="$value"
        shift
        ;;
      -s | --storefront-url)
        storefront_url="$value"
        shift
        ;;
      -t | --type)
        xd_type="$value"
        shift
        ;;
      -u | --username)
        username="$value"
        shift
        ;;
      # Arg with value
      # -x | --example)
      #   example="$value"
      #   shift
      #   ;;
      # Arg without value
      # -e | --example-flag)
      #   example_flag='true'
      #   ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$meshblu_json_path" ]; then
          meshblu_json_path="$param"
        # elif [ -z "$main_arg_2"]; then
        #   main_arg_2="$param"
        fi
        ;;
    esac
    shift
  done

  domain="${domain:-"CITRITE"}"
  name="${name:-"Smart Spaces POC - Server 2016"}"
  storefront_url="${storefront_url:-"https://alpha.xendesktop.eng.citrite.net/Citrix/ExternalWeb"}"
  xd_type="${xd_type:-"Citrix.MPS.Desktop"}"

  assert_required_params "$meshblu_json_path" "$room_uuid" "$domain" "$name" "$password" "$storefront_url" "$xd_type" "$username"
  run "$meshblu_json_path" "$room_uuid" "$domain" "$name" "$password" "$storefront_url" "$xd_type" "$username"
}

main "$@"
