#!/bin/bash

SCRIPT_NAME='make-errors-device'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == $DEBUG ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_required_params() {
  local meshblu_json_path="$1"

  if [ -n "$meshblu_json_path" ]; then
    return 0
  fi

  usage

  if [ -z "$meshblu_json_path" ]; then
    echo "Missing [/path/to/meshblu.json] argument"
  fi

  exit 1
}

usage(){
  echo "USAGE: ${SCRIPT_NAME} [/path/to/meshblu.json]"
  echo ''
  echo 'Description: ...'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help       print this help text'
  echo '  -v, --version    print the version'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

make_errors_device() {
  local meshblu_json_path="$1"
  local device_uuid
  local errors_uuid

  mkdir -p errors \
  && device_uuid="$(jq --raw-output '.uuid' "$meshblu_json_path")" \
  && meshblu-util register > errors/meshblu.json \
  && errors_uuid="$(jq --raw-output '.uuid' errors/meshblu.json)" \
  && meshblu-util update -pd "{\"\$addToSet\": {\"meshblu.whitelists.message.from\": {\"uuid\": \"$device_uuid\"}}}" errors/meshblu.json \
  && meshblu-util subscription-create --type message.received errors/meshblu.json \
  && meshblu-util update -pd "{\"\$set\": {\"commandAndControl.errorDevice.uuid\": \"$errors_uuid\", \"commandAndControl.errorDevice.logLevel\": \"error\"}, \"\$unset\": {\"commandAndControl.errorDeviceId\": true}}" "$meshblu_json_path"
}

main() {
  # Define args up here
  local meshblu_json_path

  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      # Arg with value
      # -x | --example)
      #   example="$value"
      #   shift
      #   ;;
      # Arg without value
      # -e | --example-flag)
      #   example_flag='true'
      #   ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$meshblu_json_path" ]; then
          meshblu_json_path="$param"
        # elif [ -z "$room_uuid"]; then
        #   room_uuid="$param"
        fi
        ;;
    esac
    shift
  done

  if [ -z "$meshblu_json_path" ]; then
    meshblu_json_path="./meshblu.json"
  fi

  assert_required_params "$meshblu_json_path"
  make_errors_device "$meshblu_json_path"
  exit $?
}

main "$@"
